
import React from 'react';
import type { Conversation, FileAttachment } from '../types';
import { PaperclipIcon, DownloadIcon } from './icons';
import { formatDistanceToNow } from 'date-fns';
import { useAppState } from '../contexts/AppContext';

interface DocumentsProps {
    conversations: Conversation[];
}

interface DocumentInfo {
    file: FileAttachment;
    conversationId: string;
    conversationName: string;
    timestamp: string;
}

const Documents: React.FC<DocumentsProps> = ({ conversations }) => {
    const { currentUser } = useAppState();

    const allDocuments = React.useMemo(() => {
        if (!currentUser) return [];
        const documents: DocumentInfo[] = [];
        conversations.forEach(convo => {
            const participant = convo.participants.find(p => p.id !== currentUser.id) || convo.participants[0];
            convo.messages.forEach(msg => {
                if (msg.type === 'files' && msg.files) {
                    msg.files.forEach(file => {
                        documents.push({
                            file,
                            conversationId: convo.id,
                            conversationName: convo.title || participant?.name || 'Unknown Chat',
                            timestamp: msg.timestamp,
                        });
                    });
                }
            });
        });
        return documents.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
    }, [conversations, currentUser]);

    return (
        <div className="p-6 cardSurface">
            <h1 className="text-2xl font-bold mb-6 text-zinc-100 flex items-center gap-2">
                <PaperclipIcon className="w-6 h-6 text-orange-400" /> My Documents
            </h1>
            {allDocuments.length > 0 ? (
                <div className="space-y-3">
                    {allDocuments.map((doc, index) => (
                        <div key={`${doc.conversationId}-${index}`} className="bg-zinc-800 p-3 rounded-lg flex items-center gap-4 border border-zinc-700">
                            <PaperclipIcon className="w-6 h-6 text-zinc-400 flex-shrink-0" />
                            <div className="flex-grow overflow-hidden">
                                <a href={doc.file.url} download={doc.file.name} className="text-sm font-semibold text-orange-400 hover:underline truncate block">{doc.file.name}</a>
                                <p className="text-xs text-zinc-500">
                                    {doc.file.size} - from {doc.conversationName} - {formatDistanceToNow(new Date(doc.timestamp), { addSuffix: true })}
                                </p>
                            </div>
                            <a href={doc.file.url} download={doc.file.name} className="bg-zinc-600 hover:bg-zinc-500 p-2 rounded-full transition-colors" aria-label={`Download ${doc.file.name}`}>
                                <DownloadIcon className="w-5 h-5 text-zinc-200" />
                            </a>
                        </div>
                    ))}
                </div>
            ) : (
                <div className="text-center text-zinc-500 py-16">
                    <PaperclipIcon className="w-12 h-12 mx-auto text-zinc-600"/>
                    <p className="mt-2 font-semibold">No documents yet</p>
                    <p className="text-sm">Documents generated by Aria or shared in chats will appear here.</p>
                </div>
            )}
        </div>
    );
};

export default Documents;
